name: SML_Trio-Anggoro_Preprocessing

# Memberikan izin kepada bot untuk melakukan push/write ke repository
permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Menyiapkan Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Menginstall library yang dibutuhkan script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      # 4. Menjalankan script preprocessing yang telah dibuat
      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_Trio_Anggoro.py

      # 5. Menyimpan hasil (CSV baru) kembali ke repository
      - name: Commit and Push Processed Data
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # Tambahkan file hasil generate ke staging git
          git add preprocessing/Telco-Customer-Churn_preprocessing.csv
          
          # Commit jika ada perubahan, jika tidak ada perubahan (data sama) maka skip error
          git commit -m "Auto-update: Preprocessed dataset generated by CI" || echo "No changes to commit"
          
          # Push kembali ke branch main
          git push origin HEAD:main
